// This file registers the service worker generated by VitePWA.
// It intentionally avoids caching API responses and only handles assets + updates.

export function registerSW() {
  if (typeof window === 'undefined' || !('serviceWorker' in navigator)) return;
  // Only register in production builds
  if (!import.meta.env.PROD) return;

  const swUrl = '/sw.js';
  navigator.serviceWorker.register(swUrl).then((reg) => {
    console.log('Service worker registered:', reg);
    // Optional: listen for updates
    reg.addEventListener('updatefound', () => {
      const newWorker = reg.installing;
      if (!newWorker) return;
      newWorker.addEventListener('statechange', () => {
        if (newWorker.state === 'installed') {
          // New content available; you could notify the admin to refresh
          console.log('New Service Worker installed.');
        }
      });
    });
  }).catch((err) => console.warn('SW registration failed', err));
}
