/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AvrilAdminRouteImport } from './routes/avril-admin'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as ConfigureRouteImport } from './routes/configure'
import { Route as ConfigureIdRouteImport } from './routes/configure.$id'
import { Route as ConfiguratorRouteImport } from './routes/configurator'
import { Route as ProductRouteImport } from './routes/product'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminDesignsRouteImport } from './routes/admin.designs'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AvrilAdminRoute = AvrilAdminRouteImport.update({
  id: '/avril-admin',
  path: '/avril-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigureRoute = ConfigureRouteImport.update({
  id: '/configure',
  path: '/configure',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigureIdRoute = ConfigureIdRouteImport.update({
  id: '/configure/:id',
  path: ':id',
  getParentRoute: () => ConfigureRoute,
} as any)
const ConfiguratorRoute = ConfiguratorRouteImport.update({
  id: '/configurator',
  path: '/configurator',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/:id',
  path: ':id',
  getParentRoute: () => ProductRoute,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDesignsRoute = AdminDesignsRouteImport.update({
  id: '/designs',
  path: '/designs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/avril-admin': typeof AvrilAdminRoute
  '/categories': typeof CategoriesRoute
  '/collections': typeof CollectionsRoute
  '/configure': typeof ConfigureRoute
  '/configure/:id': typeof ConfigureIdRoute
  '/configurator': typeof ConfiguratorRoute
  '/product': typeof ProductRoute
  '/product/:id': typeof ProductIdRoute
  '/contact': typeof ContactRoute
  '/offers': typeof OffersRoute
  '/order-success': typeof OrderSuccessRoute
  '/templates': typeof TemplatesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/designs': typeof AdminDesignsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/avril-admin': typeof AvrilAdminRoute
  '/categories': typeof CategoriesRoute
  '/collections': typeof CollectionsRoute
  '/configure': typeof ConfigureRoute
  '/configure/:id': typeof ConfigureIdRoute
  '/configurator': typeof ConfiguratorRoute
  '/product': typeof ProductRoute
  '/contact': typeof ContactRoute
  '/offers': typeof OffersRoute
  '/order-success': typeof OrderSuccessRoute
  '/templates': typeof TemplatesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/designs': typeof AdminDesignsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/avril-admin': typeof AvrilAdminRoute
  '/categories': typeof CategoriesRoute
  '/collections': typeof CollectionsRoute
  '/configure': typeof ConfigureRoute
  '/configure/:id': typeof ConfigureIdRoute
  '/configurator': typeof ConfiguratorRoute
  '/product': typeof ProductRoute
  '/contact': typeof ContactRoute
  '/offers': typeof OffersRoute
  '/order-success': typeof OrderSuccessRoute
  '/templates': typeof TemplatesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/designs': typeof AdminDesignsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/avril-admin'
    | '/categories'
    | '/collections'
    | '/configure'
    | '/configurator'
    | '/contact'
    | '/offers'
    | '/order-success'
    | '/templates'
    | '/admin/customers'
    | '/admin/designs'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/avril-admin'
    | '/categories'
    | '/collections'
    | '/configure'
    | '/configurator'
    | '/contact'
    | '/offers'
    | '/order-success'
    | '/templates'
    | '/admin/customers'
    | '/admin/designs'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/avril-admin'
    | '/categories'
    | '/collections'
    | '/configure'
    | '/configurator'
    | '/contact'
    | '/offers'
    | '/order-success'
    | '/templates'
    | '/admin/customers'
    | '/admin/designs'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  AvrilAdminRoute: typeof AvrilAdminRoute
  CategoriesRoute: typeof CategoriesRoute
  CollectionsRoute: typeof CollectionsRoute
  ConfigureRoute: typeof ConfigureRoute
  ContactRoute: typeof ContactRoute
  OffersRoute: typeof OffersRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  TemplatesRoute: typeof TemplatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avril-admin': {
      id: '/avril-admin'
      path: '/avril-admin'
      fullPath: '/avril-admin'
      preLoaderRoute: typeof AvrilAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configure': {
      id: '/configure'
      path: '/configure'
      fullPath: '/configure'
      preLoaderRoute: typeof ConfigureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configurator': {
      id: '/configurator'
      path: '/configurator'
      fullPath: '/configurator'
      preLoaderRoute: typeof ConfiguratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
    id: '/contact'
    path: '/contact'
    fullPath: '/contact'
    preLoaderRoute: typeof ContactRouteImport
    parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/designs': {
      id: '/admin/designs'
      path: '/designs'
      fullPath: '/admin/designs'
      preLoaderRoute: typeof AdminDesignsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDesignsRoute: typeof AdminDesignsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDesignsRoute: AdminDesignsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  AvrilAdminRoute: AvrilAdminRoute,
  CategoriesRoute: CategoriesRoute,
  CollectionsRoute: CollectionsRoute,
  ConfigureRoute: ConfigureRoute,
  ConfiguratorRoute: ConfiguratorRoute,
  ContactRoute: ContactRoute,
  OffersRoute: OffersRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  TemplatesRoute: TemplatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
